version: '3.8'

services:
  mysql:
    image: mysql:latest
    command:
      - '--skip-log-bin'                  # Bỏ qua binary logs
      - '--expire-logs-days=7'            # Xóa binary logs cũ hơn 7 ngày
      - '--max-binlog-size=104857600'     # Giới hạn kích thước binary log là 100MB
      - '--innodb-log-file-size=104857600' # Giới hạn kích thước log file của InnoDB là 100MB
      - '--general-log=0'                 # Tắt general query log
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      AMQP_URL: 'amqp://localhost?connection_attempts=5&retry_delay=5'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network

  # neo4j:
  #   image: neo4j:5.23
  #   restart: always
  #   environment:
  #     NEO4J_AUTH: neo4j/12345678  # neo4j la username, 12345678 la password
  #     NEO4J_PLUGINS: '[ "graph-data-science", "apoc" ]'  
  #   ports:
  #     - "7474:7474"  # web interface
  #     - "7687:7687"  # Bolt protocol (use for client)
  #   volumes:
  #     - neo4j_data:/data
  #     - neo4j_logs:/logs
  #   networks:
  #     - network

networks:
  network: {}

volumes:
  mysql_data:
  # neo4j_data:
  # neo4j_logs:
