// <auto-generated />
using System;
using EducationTech.DataAccess.Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducationTech.Migrations
{
    [DbContext(typeof(EducationTechContext))]
    [Migration("20241117155107_AddForgeinKeyInCommentTable")]
    partial class AddForgeinKeyInCommentTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.AnswerLearner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<int>("QuizResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("LearnerId");

                    b.HasIndex("QuizResultId");

                    b.ToTable("AnswerLearners");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DiscussionId")
                        .HasColumnType("int");

                    b.Property<int>("Left")
                        .HasColumnType("int");

                    b.Property<int?>("RepliedCommentId")
                        .HasColumnType("int");

                    b.Property<int>("Right")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("RepliedCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Comunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("Comunities");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Discussion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ComunityId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ComunityId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LearningObjectId")
                        .HasColumnType("int");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearningObjectId")
                        .IsUnique();

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.QuizResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TimeTaken")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.UserKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserKeys");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("LearningObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("LearningObjectId")
                        .IsUnique();

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CourseGroupId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecommendedSemester")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseCode")
                        .IsUnique();

                    b.HasIndex("CourseGroupId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.CourseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MinCredits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CourseGroups");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.CourseLearningPathOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("CourseId", "LearnerId")
                        .IsUnique();

                    b.ToTable("CourseLearningPathOrders");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.CourseSpeciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("CourseSpecialities");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.Learner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Learners");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.LearnerLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<int>("LearningObjectId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TimeTaken")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("LearningObjectId");

                    b.ToTable("LearnerLogs");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.LearningObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("MaxLearningTime")
                        .HasColumnType("int");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("LearningObjects");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.LearningObjectLearningPathOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<int>("LearningObjectId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("LearningObjectId", "LearnerId")
                        .IsUnique();

                    b.ToTable("LearningObjectLearningPathOrders");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.PrerequisiteCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("PrerequisiteCourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PrerequisiteCourseId");

                    b.ToTable("PrerequisiteCourses");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.RecommendTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("RecommendTopics");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.TopicLearningPathOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("TopicId", "LearnerId")
                        .IsUnique();

                    b.ToTable("TopicLearningPathOrders");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Answer", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Business.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.AnswerLearner", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Business.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.Learner", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Business.QuizResult", "QuizResult")
                        .WithMany()
                        .HasForeignKey("QuizResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Learner");

                    b.Navigation("QuizResult");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Comment", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Business.Discussion", "Discussion")
                        .WithMany("Comments")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Business.Comment", "RepliedComment")
                        .WithMany()
                        .HasForeignKey("RepliedCommentId");

                    b.HasOne("EducationTech.DataAccess.Entities.Master.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discussion");

                    b.Navigation("RepliedComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Comunity", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Master.Course", "Course")
                        .WithOne("Comunity")
                        .HasForeignKey("EducationTech.DataAccess.Entities.Business.Comunity", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Discussion", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Business.Comunity", "Comunity")
                        .WithMany()
                        .HasForeignKey("ComunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Master.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comunity");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Image", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Master.UploadedFile", "File")
                        .WithOne("Image")
                        .HasForeignKey("EducationTech.DataAccess.Entities.Business.Image", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Question", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Business.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Quiz", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.LearningObject", "LearningObject")
                        .WithOne("Quiz")
                        .HasForeignKey("EducationTech.DataAccess.Entities.Business.Quiz", "LearningObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningObject");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.QuizResult", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.Learner", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Business.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.UserKey", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Master.User", "User")
                        .WithOne("UserKey")
                        .HasForeignKey("EducationTech.DataAccess.Entities.Business.UserKey", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Video", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Master.UploadedFile", "File")
                        .WithOne("Video")
                        .HasForeignKey("EducationTech.DataAccess.Entities.Business.Video", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.LearningObject", "LearningObject")
                        .WithOne("Video")
                        .HasForeignKey("EducationTech.DataAccess.Entities.Business.Video", "LearningObjectId");

                    b.Navigation("File");

                    b.Navigation("LearningObject");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.Course", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.CourseGroup", "CourseGroup")
                        .WithMany("Courses")
                        .HasForeignKey("CourseGroupId");

                    b.HasOne("EducationTech.DataAccess.Entities.Master.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseGroup");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.RolePermission", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Master.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Master.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.UploadedFile", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Master.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.UserRole", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Master.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Master.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.CourseLearningPathOrder", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Master.Course", "Course")
                        .WithMany("CourseLearningPathOrders")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.Learner", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.CourseSpeciality", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Master.Course", "Course")
                        .WithMany("Specialities")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.Speciality", "Speciality")
                        .WithMany("Courses")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.Learner", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.Speciality", "Speciality")
                        .WithMany("Learners")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Master.User", "User")
                        .WithOne("Learner")
                        .HasForeignKey("EducationTech.DataAccess.Entities.Recommendation.Learner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speciality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.LearnerLog", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.Learner", "Learner")
                        .WithMany("LearnerLogs")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.LearningObject", "LearningObject")
                        .WithMany("LearnerLogs")
                        .HasForeignKey("LearningObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("LearningObject");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.LearningObject", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.RecommendTopic", "Topic")
                        .WithMany("LearningObjects")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.LearningObjectLearningPathOrder", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.Learner", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.LearningObject", "LearningObject")
                        .WithMany("LearningObjectLearningPathOrders")
                        .HasForeignKey("LearningObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("LearningObject");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.PrerequisiteCourse", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Master.Course", "Course")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Master.Course", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.RecommendTopic", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Master.Course", "Course")
                        .WithMany("Topics")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.Speciality", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.Branch", "Branch")
                        .WithMany("Specialities")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.TopicLearningPathOrder", b =>
                {
                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.Learner", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationTech.DataAccess.Entities.Recommendation.RecommendTopic", "Topic")
                        .WithMany("TopicLearningPathOrders")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Discussion", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Business.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.Course", b =>
                {
                    b.Navigation("Comunity")
                        .IsRequired();

                    b.Navigation("CourseLearningPathOrders");

                    b.Navigation("Prerequisites");

                    b.Navigation("Specialities");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.UploadedFile", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Master.User", b =>
                {
                    b.Navigation("Learner");

                    b.Navigation("UserKey")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.Branch", b =>
                {
                    b.Navigation("Specialities");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.CourseGroup", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.Learner", b =>
                {
                    b.Navigation("LearnerLogs");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.LearningObject", b =>
                {
                    b.Navigation("LearnerLogs");

                    b.Navigation("LearningObjectLearningPathOrders");

                    b.Navigation("Quiz");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.RecommendTopic", b =>
                {
                    b.Navigation("LearningObjects");

                    b.Navigation("TopicLearningPathOrders");
                });

            modelBuilder.Entity("EducationTech.DataAccess.Entities.Recommendation.Speciality", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Learners");
                });
#pragma warning restore 612, 618
        }
    }
}
